/* Automatic generated by './build/bin/build-entry.js' */

import Pagination from '../../node_modules/element-ui/packages/pagination/index.js';
import Dialog from '../../node_modules/element-ui/packages/dialog/index.js';
import Autocomplete from '../../node_modules/element-ui/packages/autocomplete/index.js';
import Dropdown from '../../node_modules/element-ui/packages/dropdown/index.js';
import DropdownMenu from '../../node_modules/element-ui/packages/dropdown-menu/index.js';
import DropdownItem from '../../node_modules/element-ui/packages/dropdown-item/index.js';
import Menu from '../../node_modules/element-ui/packages/menu/index.js';
import Submenu from '../../node_modules/element-ui/packages/submenu/index.js';
import MenuItem from '../../node_modules/element-ui/packages/menu-item/index.js';
import MenuItemGroup from '../../node_modules/element-ui/packages/menu-item-group/index.js';
import Input from '../../node_modules/element-ui/packages/input/index.js';
import InputNumber from '../../node_modules/element-ui/packages/input-number/index.js';
import Radio from '../../node_modules/element-ui/packages/radio/index.js';
import RadioGroup from '../../node_modules/element-ui/packages/radio-group/index.js';
import RadioButton from '../../node_modules/element-ui/packages/radio-button/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxButton from '../../node_modules/element-ui/packages/checkbox-button/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Switch from '../../node_modules/element-ui/packages/switch/index.js';
import Select from '../../node_modules/element-ui/packages/select/index.js';
import Option from '../../node_modules/element-ui/packages/option/index.js';
import OptionGroup from '../../node_modules/element-ui/packages/option-group/index.js';
import Button from '../../node_modules/element-ui/packages/button/index.js';
import ButtonGroup from '../../node_modules/element-ui/packages/button-group/index.js';
import Table from '../packages/table/index.js';
import TableColumn from '../packages/table-column/index.js';
import DatePicker from '../../node_modules/element-ui/packages/date-picker/index.js';
import TimeSelect from '../../node_modules/element-ui/packages/time-select/index.js';
import TimePicker from '../../node_modules/element-ui/packages/time-picker/index.js';
import Popover from '../../node_modules/element-ui/packages/popover/index.js';
import Tooltip from '../packages/tooltip/index.js';
import MessageBox from '../../node_modules/element-ui/packages/message-box/index.js';
import Breadcrumb from '../../node_modules/element-ui/packages/breadcrumb/index.js';
import BreadcrumbItem from '../../node_modules/element-ui/packages/breadcrumb-item/index.js';
import Form from '../../node_modules/element-ui/packages/form/index.js';
import FormItem from '../../node_modules/element-ui/packages/form-item/index.js';
import Tabs from '../../node_modules/element-ui/packages/tabs/index.js';
import TabPane from '../../node_modules/element-ui/packages/tab-pane/index.js';
import Tag from '../packages/tag/index.js';
import Tree from '../../node_modules/element-ui/packages/tree/index.js';
import Alert from '../../node_modules/element-ui/packages/alert/index.js';
import Notification from '../../node_modules/element-ui/packages/notification/index.js';
import Slider from '../../node_modules/element-ui/packages/slider/index.js';
import Loading from '../../node_modules/element-ui/packages/loading/index.js';
import Icon from '../../node_modules/element-ui/packages/icon/index.js';
import Row from '../../node_modules/element-ui/packages/row/index.js';
import Col from '../../node_modules/element-ui/packages/col/index.js';
import Upload from '../../node_modules/element-ui/packages/upload/index.js';
import Progress from '../../node_modules/element-ui/packages/progress/index.js';
import Spinner from '../../node_modules/element-ui/packages/spinner/index.js';
import Message from '../../node_modules/element-ui/packages/message/index.js';
import Badge from '../../node_modules/element-ui/packages/badge/index.js';
import Card from '../../node_modules/element-ui/packages/card/index.js';
import Rate from '../../node_modules/element-ui/packages/rate/index.js';
import Steps from '../../node_modules/element-ui/packages/steps/index.js';
import Step from '../../node_modules/element-ui/packages/step/index.js';
import Carousel from '../../node_modules/element-ui/packages/carousel/index.js';
import Scrollbar from '../../node_modules/element-ui/packages/scrollbar/index.js';
import CarouselItem from '../../node_modules/element-ui/packages/carousel-item/index.js';
import Collapse from '../../node_modules/element-ui/packages/collapse/index.js';
import CollapseItem from '../../node_modules/element-ui/packages/collapse-item/index.js';
import Cascader from '../../node_modules/element-ui/packages/cascader/index.js';
import ColorPicker from '../../node_modules/element-ui/packages/color-picker/index.js';
import Transfer from '../../node_modules/element-ui/packages/transfer/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  Scrollbar,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '1.4.4',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  MessageBox,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Notification,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Message,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  Scrollbar,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer
};
